### ISSUE TITLE
maven.danielgergely.com cert expired

### ISSUE THREAD

**Issue by xian** [gergelydaniel/kgl#14]
```
      > Could not resolve com.danielgergely.kgl:kgl:0.6.1.
         > Could not get resource 'https://maven.danielgergely.com/releases/com/danielgergely/kgl/kgl/0.6.1/kgl-0.6.1.pom'.
            > Could not GET 'https://maven.danielgergely.com/releases/com/danielgergely/kgl/kgl/0.6.1/kgl-0.6.1.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.5.1/userguide/build_environment.html#gradle_system_properties
                  > PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
```

> This server could not prove that it is maven.danielgergely.com; its security certificate expired 25 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Saturday, February 11, 2023. Does that look right? If not, you should correct your system's clock and then refresh this page.

**Comment by gergelydaniel** [comment]
Fixed it, should be good now.

I'll consider doing Maven Central releases soon, that should be more stable in the long term

**Comment by xian** [comment]
Thank you!

**Comment by SiriusZael** [comment]
hey there, looks like this issue is back

      > Could not resolve com.danielgergely.kgl:kgl:0.6.1.
         > Could not get resource 'https://maven.danielgergely.com/releases/com/danielgergely/kgl/kgl/0.6.1/kgl-0.6.1.pom'.
            > Could not GET 'https://maven.danielgergely.com/releases/com/danielgergely/kgl/kgl/0.6.1/kgl-0.6.1.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.5.1/userguide/build_environment.html#gradle_system_properties
                  > PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed

**Comment by gergelydaniel** [comment]
Sorry for that, check now pls
Will set up a cronjob for that

**Comment by SiriusZael** [comment]
sweet, we're back up, thanks!
